### ISSUE TITLE
[UAVCAN/socketcan] Compilation error `CanardFrame`has no longer member `timestamp_usec`

### ISSUE THREAD

**Issue by aentinger** [OpenCyphal-Garage/platform_specific_components#39]
This [line](https://github.com/UAVCAN/platform_specific_components/blob/master/socketcan/libcanard/src/socketcan.c#L262) causes a compile error when using with the [latest version of libcanard](https://github.com/UAVCAN/libcanard/blob/master/libcanard/canard.h#L176-L190).

**Comment by pavel-kirienko** [comment]
See if this helps: #38

**Comment by pavel-kirienko** [comment]
@aentinger would you like to volunteer some help with #38?

**Comment by aentinger** [comment]
I might, but not prior to mid-june, as I'm currently pretty occupied with slapping together software for a certain event. It was during this slap-together process that this issue came to my notice but for now I'm fine just commenting the offending line out.
